[package]
name = "clean"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.98", default-features = false }
dom_smoothie = { version = "0.11.0", default-features = false }
ureq = "3.0.12"
url = "2.5.4"
